"""Standard governance project cards, seeded once per phase.

Extracted verbatim from the original init_db() so the Dutch curriculum text is
unchanged. Structure per phase:

    'cards':        list of (title, order_index, items_or_None)
    'shared_items': items used by every card in the phase that passes None

Each item is (title, norm, middelen).
"""

from __future__ import annotations

GOVERNANCE_PHASES = {
    'startpunt': {
        'order': 1,
        'cards': [
            ('Projectkaart 1: Communicatie', 1, [
                ('Projecttitel', None, None),
                ('Doel van het project', None, None),
                ('Onderwijsinstelling', None, None),
                ('Link naar AI-onboardingsbot', None, None),
                ('Link naar het overdrachtsdocument', None, None),
                ('Belangrijkste deliverables', None, None),
                ('Betrokken stakeholders', None, None),
            ]),
            ('Projectkaart 1: Werkveld', 2, [
                ('Projecttitel', None, None),
                ('Doel van het project', None, None),
                ('Onderwijsinstelling', None, None),
                ('Link naar AI-onboardingsbot', None, None),
                ('Belangrijkste deliverables', None, None),
                ('Betrokken stakeholders', None, None),
            ]),
            ('Projectkaart 1: Evenementen', 3, [
                ('Projecttitel', None, None),
                ('Doel van het project', None, None),
                ('Onderwijsinstelling', None, None),
                ('Link naar AI-onboardingsbot', None, None),
                ('Link naar het overdrachtsdocument', None, None),
                ('Belangrijkste deliverables', None, None),
                ('Betrokken stakeholders', None, None),
            ]),
            ('Projectkaart 1: Onderwijs', 4, [
                ('Projecttitel', None, None),
                ('Doel van het project', None, None),
                ('Onderwijsinstelling', None, None),
                ('Link naar AI-onboardingsbot', None, None),
                ('Belangrijkste deliverables', None, None),
                ('Betrokken stakeholders', None, None),
            ]),
        ],
    },
    'empathize': {
        'order': 2,
        'cards': [
            ('Projectkaart 2: Communicatie', 1, None),
            ('Projectkaart 2: Werkveld', 2, None),
            ('Projectkaart 2: Evenementen', 3, None),
            ('Projectkaart 2: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Doelen en succescriteria van deze fase zijn opgesteld',
             'Er is een kort document (max. 1 A4) op Teams waarin de student beschrijft wat hij/zij onderzocht wil hebben, bereiken en ophalen in deze fase. Dit is afgestemd met de DS specialist.',
             None),
            ('Gebruikersonderzoek uitvoeren (intern en extern)',
             'Minimaal 3 interviews met stakeholders zijn afgenomen en samengevat (met citaten of kerninzichten).',
             'Interviewvragenlijst (HGO-format), opnames / Teams-call'),
            ('Observaties in de praktijk zijn uitgevoerd',
             'Minimaal één praktijkobservatie is gedocumenteerd, inclusief datum, setting, observaties en reflectie.',
             'Observatieformulier'),
            ('Analyse van bestaand materiaal is uitgevoerd (desk research)',
             'Ten minste drie bestaande bronnen zijn geanalyseerd en samengevat in eigen woorden, met verwijzing naar relevante HGO-content.',
             'HGO-kennisbank, ToekomstTV, Teams-projectarchief, HAN studie centrum'),
            ("Empathy Mapping en Persona's zijn opgesteld",
             "Minstens één uitgewerkte empathy map en één persona (met naam, quote, behoeften, frustraties, context) zijn gedeeld in het clusterkanaal.",
             'Canva | Miro | PowerPoint | Word'),
            ('Stakeholders zijn gesproken',
             'Er is een overzicht gemaakt van alle relevante stakeholders met status van contact (gesproken, gepland, niet bereikbaar). Minimaal 3 zijn inhoudelijk gesproken.',
             'Stakeholderoverzicht | Teams | Planner'),
            ('Data over de fase is verzameld en verwerkt in de online werkomgeving op Teams',
             "Alle interviews, observaties, analyses en persona's zijn opgeslagen in de juiste mapstructuur op Teams en gedeeld met het cluster.",
             None),
            ('Persoonlijke Teams planner aan de hand van Design Thinking is ingevuld',
             'De student heeft in Microsoft Planner minimaal 5 taken aangemaakt per fase die gekoppeld zijn aan de DS-fases. Taken zijn voorzien van beschrijving en deadlines.',
             'Microsoft Planner, Scrum en deconstructie'),
            ('Progres meetings zijn ingepland met DS-specialist en mits nodig afdelingshoofd voor iedere fase van het project',
             'De student heeft via Outlook 1 check-in gepland met DS-specialist en bij complexe projecten ook met de afdelingshoofd. Notulen/reflectie worden gedeeld in Teams. Bij de uitnodiging van de meeting zit een agenda.',
             'Outlook Agenda, Microsoft Teams'),
        ],
    },
    'define': {
        'order': 3,
        'cards': [
            ('Projectkaart 3: Communicatie', 1, None),
            ('Projectkaart 3: Werkveld', 2, None),
            ('Projectkaart 3: Evenementen', 3, None),
            ('Projectkaart 3: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Doelen en succescriteria van deze fase zijn opgesteld',
             'Er is een kort document (max. 1 A4) op Teams waarin de student beschrijft wat hij/zij onderzocht wil hebben, bereiken en ophalen in deze fase. Dit is afgestemd met de DS-specialist.',
             None),
            ('Probleemdefinitie is geformuleerd op basis van data & inzichten',
             'De stagiaire heeft een beargumenteerde probleemdefinitie geschreven van max. 10 regels, gebaseerd op data uit de Empathise-fase. Deze is gedeeld in Teams en terug te vinden in het projectdossier.',
             None),
            ('Er is een huidige schets van het proces/event en een gewenste schets van het nieuwe resultaat',
             None,
             'Alle data uit je empathize fase'),
            ('Stakeholdermap is gemaakt',
             'Er is een visuele of tekstuele stakeholdermap gemaakt met minimaal 6 actoren, inclusief rol, invloed en betrokkenheid. Deze is opgeslagen en gedeeld in Teams.',
             'Stakeholder Canvas, Miro / Canva / PowerPoint'),
            ('Kaders zijn bepaald vanuit HAN-koers & HGO-visie',
             'De koppeling met ten minste één HAN-koersdoel (Slim, Schoon, Sociaal of Wereldburgerschap) en de HGO-visie is expliciet beschreven en zichtbaar in de probleemdefinitie of begeleidend verslag.',
             'HAN Koersbeeld-document, Kennisdocument HGO'),
            ('Probleemdefinitie is uitgewerkt met mogelijke samenwerking',
             'De student heeft de probleemstelling gepresenteerd in een clusteroverleg of progressmeeting en heeft opties voor samenwerking benoemd. Feedback is verwerkt in een bijgewerkte versie.',
             'Pitchdeck of poster, feedbackformulier, PowerPoint | Canva, Teams of Word'),
            ('Data over de fase is verzameld en verwerkt in de online werkomgeving op Teams',
             "Alle interviews, observaties, analyses en persona's zijn opgeslagen in de juiste mapstructuur op Teams en gedeeld met het cluster.",
             None),
            ('Het eerste school product is ingeleverd',
             'Als school een plan van aanpak, projectplan, methodiek, draaiboek etc is gemaakt en ingeleverd.',
             'Alle data van de empathise en define fases van DS'),
        ],
    },
    'ideate': {
        'order': 4,
        'cards': [
            ('Projectkaart 4: Communicatie', 1, None),
            ('Projectkaart 4: Werkveld', 2, None),
            ('Projectkaart 4: Evenementen', 3, None),
            ('Projectkaart 4: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Doelen en succescriteria van deze fase zijn opgesteld',
             'Er is een kort document (max. 1 A4) op Teams waarin de student beschrijft wat hij/zij onderzocht wil hebben, bereiken en ophalen in deze fase. Dit is afgestemd met de DS-specialist.',
             None),
            ('Creatieve brainstormsessie is georganiseerd',
             "Er is minstens één brainstormsessie gefaciliteerd met teamleden of stakeholders, en de output hiervan (bv. notities, post-its, whiteboardfoto's) is vastgelegd.",
             "Miro | Mural | Canva | Whiteboardfoto's, Werkvormen als SCAMPER, Crazy 8's, Brainwriting"),
            ('Er zijn minimaal 3 oplossingsrichtingen/ontwerpen geschetst (divergent denken)',
             'De student heeft drie verschillende concepten uitgewerkt, ieder met een korte beschrijving en/of visuele ondersteuning (tekening, schema, storyboard).',
             'PowerPoint | Canva | Sketch | AI-generated visuals | Word | Designcanvas'),
            ("Er is een feedbackronde georganiseerd ('How Might We' / Prototype Feedback)",
             "De student heeft feedback opgehaald op de gegenereerde ideeën via interviews, peer-review of clusterpresentatie, en deze feedback is verwerkt in een overzicht.",
             'Feedbackformulier | Miro-board | Teamoverlegnotities | Reflectieverslag'),
            ('Het kernidee is gekozen en beargumenteerd',
             'De student heeft een onderbouwde keuze gemaakt voor één oplossingsrichting, met een korte beargumentering (impact, haalbaarheid, aansluiting op koers & visie).',
             'Impactmatrix | SWOT | Besliscanvas | Pitchdeck of Word-document met argumentatie'),
            ('Data over de fase is verzameld en verwerkt in de online werkomgeving op Teams',
             "Alle interviews, observaties, analyses en persona's zijn opgeslagen in de juiste mapstructuur op Teams en gedeeld met het cluster.",
             None),
        ],
    },
    'prototype': {
        'order': 5,
        'cards': [
            ('Projectkaart 5: Communicatie', 1, None),
            ('Projectkaart 5: Werkveld', 2, None),
            ('Projectkaart 5: Evenementen', 3, None),
            ('Projectkaart 5: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Doelen en succescriteria van deze fase zijn opgesteld',
             'Er is een kort document (max. 1 A4) op Teams waarin de stagiair beschrijft wat hij/zij onderzocht wil hebben, bereiken en ophalen in deze fase. Dit is afgestemd met de DS-specialist.',
             None),
            ('Kern(functionaliteit) zijn gekozen',
             'De stagiair heeft één duidelijke focus geformuleerd: welk onderdeel of gedrag moet getest worden? Dit is vastgelegd in het prototypeplan.',
             None),
            ('Schetsmatig prototype zijn gemaakt',
             'Er is een eerste ruwe uitwerking gemaakt van het prototype (bv. op papier, in PowerPoint of via een visuele tool), inclusief uitleg van het doel.',
             "Miro | Canva | Figma | PowerPoint | Foto's van schetsen | Word"),
            ('Prototype is gebouwd (indien passend)',
             'Indien relevant, is een werkende versie van het prototype gemaakt (bv. werkende AI-tool, interactieve lesvorm, gameconcept, communicatie-uiting).',
             "GPT / Gemini | Figma | Canva | Workshopformat | Digitale toolomgeving | Custom GPT's (via Seyma)"),
            ('Prototype is geïntegreerd in HGO-context',
             'Het prototype sluit aan bij bestaande structuren binnen HGO (bijv. tools, formats, games, events). Er is overleg geweest met een clusterlead of coach over inbedding.',
             'Productportfolio HGO | Clusteroverleg | Feedback van coach of lead | Beschrijving in Word/Teams'),
            ('Testopzet is voorbereid',
             'Er is een korte testopzet uitgewerkt met testdoel, doelgroep, manier van testen en verwachte output. Deze is opgeslagen op Teams.',
             'Testplan-sjabloon, Word | Notion | Canva/PowerPoint voor visuals | Checklist observatie'),
            ('Test is uitgevoerd en vastgelegd',
             'Het prototype is getest met minimaal 1 echte gebruiker of groep. Data (observaties, reacties, scores) is verzameld en opgeslagen.',
             "Observatieformulieren, feedbackformulieren, foto's/video, verslag in Word of Notion, Teams-opslag"),
            ('Reflectie en doorontwikkeling is gemaakt',
             'De stagiair heeft een korte reflectie geschreven over wat werkte, wat niet, en wat moet worden aangepast in de volgende fase.',
             'Reflectiesjabloon, Word | Notion | AI (GPT) voor samenvattende analyse van testdata'),
            ('Data over de fase is verzameld en verwerkt in de online werkomgeving op Teams',
             "Alle interviews, observaties, analyses en persona's zijn opgeslagen in de juiste mapstructuur op Teams en gedeeld met het cluster.",
             None),
        ],
    },
    'test': {
        'order': 6,
        'cards': [
            ('Projectkaart 6: Communicatie', 1, None),
            ('Projectkaart 6: Werkveld', 2, None),
            ('Projectkaart 6: Evenementen', 3, None),
            ('Projectkaart 6: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Doelen en succescriteria van deze fase zijn opgesteld',
             'Er is een kort document (max. 1 A4) op Teams waarin de student beschrijft wat hij/zij onderzocht wil hebben, bereiken en ophalen in deze fase. Dit is afgestemd met de DS-specialist.',
             None),
            ('Pilotplan/draaiboek is opgesteld',
             'Er is een uitgewerkt plan met doelgroep, opzet, meetdoelen, feedbackmethodes en planning. Dit plan is gedeeld in Teams én besproken met een begeleider of partner.',
             'Pilotplan-sjabloon, Word/Notion, Teams-opslag | Event-draaiboek (indien van toepassing)'),
            ('Partners en stakeholders zijn betrokken',
             'Minstens 2 relevante partners zijn actief betrokken bij de voorbereiding of uitvoering van de pilot. Er is vastgelegd wie wat doet, en communicatie is verlopen via mail, Teams of overleg.',
             'Stakeholderoverzicht, Communicatielog, e-mailarchief, afspraken in Outlook'),
            ('De pilot/event is georganiseerd en uitgevoerd',
             "De pilot of testmoment is daadwerkelijk uitgevoerd. Er is bewijs (foto's, deelnemerslijst, observaties, feedback) opgeslagen in Teams. Reflectie op verloop is toegevoegd.",
             "Draaiboek | Planning in Teams/Outlook | Foto's/video | Observatieformulieren | Feedbackformulieren"),
            ('Communicatie- en borgingplan is opgesteld en gedeeld',
             'De student heeft een voorstel geschreven over hoe het resultaat geborgd kan worden binnen de HGO (in portfolio, aanbod, kennisbank of als vervolgproject), inclusief communicatie naar het team.',
             'Borgingsplan-sjabloon, PowerPoint/Canva voor interne presentatie, Word-document | Optioneel bespreking in clusteroverleg'),
            ('Data over de fase is verzameld en verwerkt in de online werkomgeving op Teams',
             "Alle interviews, observaties, analyses en persona's zijn opgeslagen in de juiste mapstructuur op Teams en gedeeld met het cluster.",
             None),
        ],
    },
    'uittreden': {
        'order': 7,
        'cards': [
            ('Projectkaart 7: Communicatie', 1, None),
            ('Projectkaart 7: Werkveld', 2, None),
            ('Projectkaart 7: Evenementen', 3, None),
            ('Projectkaart 7: Onderwijs', 4, None),
        ],
        'shared_items': [
            ('Definitieve producten of resultaten zijn opgeleverd', None, None),
            ('Resultaat is geborgd volgens opgesteld borgingsplan', None, None),
            ('Gereflecteerd op het resultaat en de impact', None, None),
            ('Gereflecteerd op het proces en de samenwerking', None, None),
        ],
    },
}
